language: node_js
node_js:
- node
deploy:
  provider: npm
  email: wwigham@gmail.com
  api_key:
    secure: jvst4NVaAOH42q5GU6xgR57lqhm5+XZusH5b96UAILe+wGGzTaV7gJJ5btph1Hxd+nXMiKeHWjartnKKq/oUFQ78XB76fEhFTNxecJfFp0vDG3TbenzfDIZBt9hAh/9A1+vE9MYg8CO1zaVA9Voi0LQSJoPePDbPRzdkfRQ2zT+Ys9SPMWBa2UPdMdIlCUTNHJKm2Cng1aPSoe1y8mH2rkwWBmETSRW1YE2J4DlkVBVw5tUysgizRIKg/5obAi56VVygEr3l5Eh9C8olIfAMfXB75KiJJEOKWMH3aMT6Ic8yXE5qHUNUbJtZqd2P2EVsKUEkzB7THsP3ygTaN9izgr6PCTjJ8fR5HkoUZ6F1wsLsgzG7KRM8hFzhugTHhGxDIHozJUJxIwoJstGDNqfwclOfnCs5rTo+6OH0EYVsiGlq5UL1Oumd3uyYXxKDviV4xcm5KARp1UGa3NUKFE1Zlx04WxhnVhzso2hVbdzDYZF2GD27/SCWYTpi698pItvEDXoUlbvoOh7CmgsrP1sP6TX+cA04QFnrJlKaEyBwoNumF/KndeDwaHVH74lJrlIbWG0mr75aJnBI2bNkqdrNu1QZpICW0lphR40Bq5hU6EBiMWHnDoJm6E6O0V/L1xw4INg1FQYGBL8aLFoJS0T3YIWM/VFpSzVv1+tT8QW11wU=
  on:
    tags: true
    repo: weswigham/eve-online-sde
script:
- npm test
- if [[ $TRAVIS_EVENT_TYPE == "cron" ]]; then git init; git config user.name "Travis
  CI"; git config user.email "wwigham@gmail.com"; git remote add upstream "https://$GH_TOKEN@github.com/weswigham/eve-online-sde";
  git fetch upstream; git checkout master; fi
- if [[ $TRAVIS_EVENT_TYPE == "cron" ]]; then npm run update-sde || travis_terminate
  1; fi
- if [[ $TRAVIS_EVENT_TYPE == "cron" ]]; then if [[ ! "$(git status -s)" =~ ^$ ]];
  then git add sde; git add package.json; git add package-lock.json; git commit -m 'Automatic SDE Update'; git
  push -u upstream master; git tag $(node ./scripts/print-version.js); git push upstream
  --tags; fi; fi
env:
  global:
    secure: jN3XXC7/JKXVQSFAOtZDTr3dCPmJkYyJGlJaiIxBIJrWON7hX0X5CG65BNOO8H45rb3GxAGeZ5XXmAkIBDZIhoc+DifCV3aUfmeTuV3wE/HT45ml+D+E3XZemWRq9F2FZGlb5ZgWK9aVcibeUMYKXV+u36rsb8asJlE7LCjlJy0chJShXiTCtigSF43QXVQYSeRIzG0IXigjfW/3uJpuVzk/AEfvZQGf+yFB6neOdPaYBEcXlFe/woU1YtF7z4hRwAkjflMPPUOA4XrroWOIkAlZQaIyqGI6I/O8ERbCceSNAJHHhgLIfrHEHYn2EA/FVOxKEQViN3aLB5HKJWzDa9zare5I/gzhbZbsV5oAFpQALs6V+nSP8GeFZ/KYwggrAeHYAk8cTM6oSaep7PCXMOaaq5Ox2cNJ68GICqq2aZ3B+NUV14R3FfR/n5hwqHK4/uwtuY42004uzc8NeYxAC7cPXSru5SzVrnYDDQXoNfoviw0wRBhWVngbChjbpOtipAApYae1DMAoUTIxcZ0LMkD020gDkUoy7X9bFGXfFkf7I8yCXfl8WFQqTaJhMqR6NSiuxq58ohMXPoAwtTXdPhZ1RQB/mOLCc6N7toPWkRS/mT2HyX9/qBjhNFKCpbsJG9HdBV/fivItktLHOrhl4k4diJV8mf2ElD66isLsArs=
