export function raw(...names: string[]): Promise<any>;
export function agents(): Promise<any>;
export function agentsInSpace(): Promise<any>;
export function ancestries(): Promise<any>;
export function bloodlines(): Promise<any>;
export function blueprints(): Promise<any>;
export function categories(): Promise<any>;
export function certificates(): Promise<any>;
export function characterAttributes(): Promise<any>;
export function contrabandTypes(): Promise<any>;
export function controlTowerResources(): Promise<any>;
export function corporationActivities(): Promise<any>;
export function dogmaAttributeCategories(): Promise<any>;
export function dogmaAttributes(): Promise<any>;
export function dogmaEffects(): Promise<any>;
export function factions(): Promise<any>;
export function graphics(): Promise<any>;
export function groups(): Promise<any>;
export function icons(): Promise<any>;
export function marketGroups(): Promise<any>;
export function metaGroups(): Promise<any>;
export function npcCorporationDivisions(): Promise<any>;
export function npcCorporations(): Promise<any>;
export function planetResources(): Promise<any>;
export function planetSchematics(): Promise<any>;
export function races(): Promise<any>;
export function researchAgents(): Promise<any>;
export function skinLicenses(): Promise<any>;
export function skinMaterials(): Promise<any>;
export function skins(): Promise<any>;
export function soverigntyUpgrades(): Promise<any>;
export function stationOperations(): Promise<any>;
export function stationServices(): Promise<any>;
export function tournamentRules(): Promise<any>;
export function typeDogma(): Promise<any>;
export function typeMaterials(): Promise<any>;
export function types(): Promise<any>;
export function landmarks(): Promise<any>;
export function region(name: string): Promise<any>;
export function lookup(name: string, lang = "en"): Promise<any>;
export function lookupByID(id: number): Promise<any>;
