name: Nightly Update

on:
  schedule:
    - cron:  '0 8 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create LFS file list
        run: git lfs ls-files --long | cut -d ' ' -f1 | sort > .lfs-assets-id
      - name: LFS Cache
        uses: actions/cache@v4
        with:
          path: .git/lfs/objects
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
          restore-keys: |
            ${{ runner.os }}-lfs-
      - name: Git LFS Pull
        run: git lfs pull
      - uses: actions/setup-node@v4
      - name: Setup
        run: npm ci
      - name: npm run update-sde
        run: npm run update-sde
      - name: Commit updates
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'weswigham@users.noreply.github.com'
          git add sde
          git add package.json
          git commit -m "Automatic SDE Update"
          git push
          git tag $(node ./scripts/print-version.js)
          git push --tags
